name: certora

on:
  push:
    branches:
      - master
    paths:
      - modules/4337/**
  pull_request:
    branches:
      - master
    paths:
      - modules/4337/**

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rule:
          ["verify4337Module.sh", "verifyTransactionExecutionMethods.sh", "verifyValidationData.sh"]
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with: { python-version: 3.11 }

      - name: Install java
        uses: actions/setup-java@v3
        with: { java-version: "17", java-package: jre, distribution: semeru }

      - name: Install certora cli
        run: pip install -Iv certora-cli

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.23/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.23

      - name: Install dependencies
        run: npm ci -ws

      - name: Verify rule ${{ matrix.rule }}
        run: |
          echo "key length" ${#CERTORAKEY}
          chmod +x ./certora/scripts/${{ matrix.rule }}
          ./certora/scripts/${{ matrix.rule }}
        env:
          CERTORAKEY: ${{ secrets.CERTORA_KEY }}
