name: safe-modules-4337
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/4337
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: modules/4337/package-lock.json
      - run: npm ci
      - run: npm run build && npm run build:ts
      - run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: modules/4337/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/4337
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: modules/4337/package-lock.json
      - run: npm ci
      - run: |
          docker compose up -d
          # wait for containers to start up
          SECONDS=0
          until curl -fs http://localhost:8545 >/dev/null && curl -fs http://localhost:3000 >/dev/null; do
            if [[ $SECONDS -gt 30 ]]; then
              echo "ERROR: timeout waiting for local node and bundler to start"
              docker compose logs
              exit 1
            fi
            sleep 1
          done

          npm run test:e2e
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/4337
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: modules/4337/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run fmt:check
